name: CI Suite
on:
  pull_request:
    branches:
    - master
    - 'project/**'
  merge_group:
    branches:
    - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_linters:
    if: ( !contains(github.event.head_commit.message, '[ci skip]') )
    name: Run Linters
    uses: ./.github/workflows/run_linters.yml

  collect_data:
    if: ( !contains(github.event.head_commit.message, '[ci skip]') )
    name: Collect data for other tasks
    uses: ./.github/workflows/collect_data.yml

  compile_all_maps:
    if: ( !contains(github.event.head_commit.message, '[ci skip]') )
    name: Compile Maps
    needs: collect_data
    uses: ./.github/workflows/compile_all_maps.yml
    with:
      max_required_byond_client: ${{ needs.collect_data.outputs.max_required_byond_client }}

  run_all_tests:
    if: ( !contains(github.event.head_commit.message, '[ci skip]') )
    name: Integration Tests
    needs: [collect_data]

    uses: ./.github/workflows/perform_regular_version_tests.yml
    with:
      maps: ${{ needs.collect_data.outputs.maps }}
      max_required_byond_client: ${{needs.collect_data.outputs.max_required_byond_client}}

  run_alternate_tests:
    if: ( !contains(github.event.head_commit.message, '[ci skip]') && needs.collect_data.outputs.alternate_tests != '[]' )
    name: Alternate Tests
    needs: collect_data

    uses: ./.github/workflows/perform_alternate_version_tests.yml
    with:
      alternate_tests: ${{ needs.collect_data.outputs.alternate_tests }}
      default_max_required_byond_client: ${{ needs.collect_data.outputs.max_required_byond_client }}

  compare_screenshots:
    if: ( !contains(github.event.head_commit.message, '[ci skip]') && ( needs.collect_data.outputs.alternate_tests == '[]' || needs.run_alternate_tests.result == 'success' )
    needs: [collect_data, run_all_tests, run_alternate_tests]
    name: Compare Screenshot Tests
    uses: ./.github/workflows/compare_screenshots.yml

  test_windows:
    if: ( !contains(github.event.head_commit.message, '[ci skip]') )
    name: Windows Build
    needs: collect_data
    uses: ./.github/workflows/test_windows.yml
    with:
      max_required_byond_client: ${{needs.collect_data.outputs.max_required_byond_client}}
